name: pickleball_match
description: PickleMatch - Find and join pickleball matches near you.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  google_sign_in: ^7.2.0
  google_sign_in_web: ^1.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
